name: Pull request
# This workflow is triggered on pull requests for the repository.
on: [pull_request]

jobs:
  clean_commit_job:
    name: Job to prevent bad commit messages
    runs-on: ubuntu-latest
    steps:
      - name: Clean commit step
        uses: actions/clean-commit-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
